### ISSUE TITLE
problems loading mnist, leeds datasets

### ISSUE THREAD

**Issue by tawnkramer** [dbcollection/dbcollection#34]
Os: Ubuntu 16.04 LTS
Python: 3.5.2

I installed first from pip and then from github. Same results below. It did download a few 78KB zip files in ~/dbcollection/leeds_sports_pos/data/, but none of them appear to be zip files that archive manger or unzip can handle. ~/dbcollection/mnist/data is empty.

-----------------------------------

Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbcollection as dbc
>>> mnist = dbc.load('mnist')
==> Download mnist data to disk...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 177, in load
    download(name, data_dir, True, verbose, is_test)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 75, in download
    keywords = dataset.download(name, data_dir_, cache_save_path, extract_data, verbose)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/funs.py", line 100, in download
    return dataset_loader.download()
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/__init__.py", line 38, in download
    shutil.copy2(fname_train_imgs, self.data_path)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/data/train-images.idx3-ubyte'
>>> mnist = dbc.load('mnist')
Create cache dir: /home/tkramer/dbcollection
==> Download mnist data to disk...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 177, in load
    download(name, data_dir, True, verbose, is_test)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 75, in download
    keywords = dataset.download(name, data_dir_, cache_save_path, extract_data, verbose)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/funs.py", line 100, in download
    return dataset_loader.download()
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/__init__.py", line 38, in download
    shutil.copy2(fname_train_imgs, self.data_path)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/data/train-images.idx3-ubyte'
>>> mnist = dbc.load('leeds_sports_pose')
==> Download leeds_sports_pose data to disk...

Download url (1/2): http://www.comp.leeds.ac.uk/mat4saj/lsp_dataset_original.zip
100% (23 of 23) |###########################################| Elapsed Time: 0:00:00 Time: 0:00:00
patool: Extracting /home/tkramer/dbcollection/leeds_sports_pose/data/lsp_dataset_original.zip ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patoolib/programs/py_zipfile.py", line 42, in extract_zip
    with zipfile.ZipFile(archive) as zfile:
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 177, in load
    download(name, data_dir, True, verbose, is_test)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py", line 75, in download
    keywords = dataset.download(name, data_dir_, cache_save_path, extract_data, verbose)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/funs.py", line 100, in download
    return dataset_loader.download()
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/dbclass.py", line 88, in download
    self.extract_data, self.verbose)
  File "/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/utils/url.py", line 257, in download_extract_all
    patoolib.extract_archive(filename, outdir=dir_save, verbosity=verbose)
  File "/usr/local/lib/python3.5/dist-packages/patoolib/__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "/usr/local/lib/python3.5/dist-packages/patoolib/__init__.py", line 479, in _extract_archive
    cmdlist = get_archive_cmdlist(archive, compression, program, verbosity, interactive, outdir)
  File "/usr/local/lib/python3.5/dist-packages/patoolib/programs/py_zipfile.py", line 46, in extract_zip
    raise util.PatoolError(msg)
patoolib.util.PatoolError: error extracting /home/tkramer/dbcollection/leeds_sports_pose/data/lsp_dataset_original.zip: File is not a zip file

**Comment by farrajota** [comment]
I'll take a look at it and I'll let you know.

**Comment by farrajota** [comment]
Ok, I've got something. 

First: I've done a fresh install of `dbcollection`(via pip and conda) on a new conda env and mnist was included. So you couldn't get any input from that.

Second: I proceeded to check why leeds sports was not working. `cifar10` downloaded and installed correctly but `leeds_sports_pose` didn't. Nothing in the code pointed to the cause of it not downloading correctly. So I took a look at the leeds sports website and... I didn't find it. The website may be down or, worse case scenario, it may be deprecated. 

Do you need this dataset? Urgently? 

Let me know and I'll see what I can do to help.

**Comment by tawnkramer** [comment]
I'm not in a super big hurry. Just researching on my own time. I usually
download the datasets from the source, but found your project and wanted to
give it a try. Wonder why mnist wouldn't load.

**Comment by farrajota** [comment]
I'll take another look at this first thing in the morning and see why you can't load mnist.

Regarding this project, there's still some stuff to do. Probably next week I'll finally have the free time I need to do stuff like documentation, website, some code overhauling, etc., so expect somethings to sort off not work as intended for now. Also, if you face any problem just post an issue and I'll glady take a look at it.

The documentation is in a miserable state right now, but you can get pretty much everything you might need from [here](https://github.com/dbcollection/dbcollection/blob/master/DOCUMENTATION.md).

**Comment by farrajota** [comment]
I've updated the urls for the `leeds_sports_pose` dataset and committed some fixes. You'll need to install it from [source](https://github.com/dbcollection/dbcollection#from-source) for now to use it. I'll bump the package's version next week, so you'll be able to install this package via `pip` or `conda` once `v0.1.8` is available (probably friday).

**Comment by tawnkramer** [comment]
Thanks! I see that leeds came down now. Still getting same error with
mnist. But not a big deal to me.

after:

cd dbcollection
git pull
sudo python3 setup.py install
cd ~/
python3
>>> import dbcollection as dbc
>>> mnist = dbc.load('mnist')
==> Download mnist data to disk...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py",
line 177, in load
    download(name, data_dir, True, verbose, is_test)
  File
"/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/manager.py",
line 75, in download
    keywords = dataset.download(name, data_dir_, cache_save_path,
extract_data, verbose)
  File
"/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/funs.py",
line 100, in download
    return dataset_loader.download()
  File
"/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/__init__.py",
line 38, in download
    shutil.copy2(fname_train_imgs, self.data_path)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory:
'/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/data/train-images.idx3-ubyte'

>>> quit()
tkramer@tkramer-HP-Z620-Workstation:~/projects$ ls
/usr/local/lib/python3.5/dist-packages/dbcollection-0.1.7-py3.5.egg/dbcollection/datasets/mnist/data/
__init__.py  __pycache__

**Comment by tawnkramer** [comment]
sorry, but I'm not seeing how to load the image data associated with the
leeds database.

import dbcollection as dbc
lsp = dbc.load('leeds_sports_pose')
print(lsp.info())

> Set: test
   - image_filenames,  shape = (1000, 18),     dtype = uint8,    (in
'object_ids', position = 0)
   - keypoint_names,   shape = (14, 15),       dtype = uint8
   - keypoints,        shape = (1000, 14, 3),  dtype = float64,  (in
'object_ids', position = 1)
   - object_fields,    shape = (2, 16),        dtype = uint8
   - object_ids,       shape = (1000, 2),      dtype = int32

> Set: train
   - image_filenames,  shape = (1000, 18),     dtype = uint8,    (in
'object_ids', position = 0)
   - keypoint_names,   shape = (14, 15),       dtype = uint8
   - keypoints,        shape = (1000, 14, 3),  dtype = float64,  (in
'object_ids', position = 1)
   - object_fields,    shape = (2, 16),        dtype = uint8
   - object_ids,       shape = (1000, 2),      dtype = int32
None

print(lsp.object_fields)

{'test': ['image_filenames', 'keypoints'], 'train':
['image_filenames', 'keypoints']}


Maybe need to obtain those image files separately and find them via
image_filenames? Having same problem with mpii_pose.

**Comment by tawnkramer** [comment]
found the images in:
/home/tkramer/dbcollection/leeds_sports_pose/data/lsp_dataset/images/

lsp.data_dir gives me this much.

/home/tkramer/dbcollection/leeds_sports_pose/data


not sure where to get the lsp_dataset string from. But I'm making it
work for me now. Thanks.

**Comment by farrajota** [comment]
Its strange that you are not able to load `mnist`. If you are not using anaconda, I suggest you to give it a try and see if the problem persists when using it (you can also use different python versions, but that shouldn't be the issue).

Now regarding data access. Fetching data can be done via two ways: via `get()` call or you can transverse the `hdf5` file via the field `.file`. The main goals of `dbcollection` is to a) provide an easy and simple way to download and parse data of a given dataset with little to no effort, and b) to provide a simple way to fetch data from it. Ofc there are other advantages of using this package, but I'll leave it to the documentation to address it (even though the documentation is still being written atm). 

Bellow there are some ways you can access data using the python's API methods, and for more information you can always check this [temporary/brief documentation](https://github.com/dbcollection/dbcollection/blob/master/DOCUMENTATION.md).

## via `get()`

To fetch data via the [get()](https://github.com/dbcollection/dbcollection/blob/master/DOCUMENTATION.md#get) method is simple. You just need to specify which set you want to fetch from and the field name. Lets use the `leeds_sports_pose_extended` dataset as an example:

```python
import os
import dbcollection as dbc
from dbcollection.utils.string_ascii import convert_ascii_to_str as tostr
from PIL import Image
import matplotlib.pyplot as plt

# return a loader of the dataset
lsp = dbc.load('leeds_sports_pose_extended')

# display how the dataset is partitioned (train + test)
print(lsp.sets)

# display all fields from the 'train' set
print(lsp.info('train'))

# fetch data from the hdf5 metadata file via get()
img_fname = lsp.get('train', 'image_filenames', 0)  # first image filename
filename = os.path.join(lsp.data_dir, tostr(img_fname))  # convert img_fname from ASCII encoding to string and craft the filename full path
img = Image.open(filename)  #load the image file
plt.imshow(img)  #plot the image
plt.show()

# display all keypoint names
print(tostr(lsp.get('train', 'keypoint_names')))
```

To fetch the right keypoint coordinates and name you'll need to use the `object_ids` field which stores the relationship between fields by ids. I'll show how to fetch data using `object_ids` next.

## via `object()` 

The [object()](https://github.com/dbcollection/dbcollection/blob/master/DOCUMENTATION.md#object) method returns a list of indexes of associated data. This is how images and keypoints, in this case, are linked. Fetching related data is easy using this method. In the next example, lets fetch the 100th object (image filename + keypoint coords):

```python
import os
import dbcollection as dbc
from dbcollection.utils.string_ascii import convert_ascii_to_str as tostr
from PIL import Image
import matplotlib.pyplot as plt

# return a loader of the dataset
lsp = dbc.load('leeds_sports_pose_extended')

# fetch data from the hdf5 metadata file using the object() method
data = lsp.object('train', 99, True)  # 100th object (True converts the fields indexes to values automatically)
img_fname =  tostr(data[0])
keypoints = data[1]
filename = os.path.join(lsp.data_dir, img_fname)

print(keypoints)  # display keypoint coordinartes of the image

img = Image.open(filename)
plt.imshow(img)
plt.show()
```

Note: this `object` method is basicaly the same as the `get` method with some extra features. 

## via direct file access

Using `file` you access directly the `hdf5` metadata file. The first example goes as follows:

```python
import os
import dbcollection as dbc
from dbcollection.utils.string_ascii import convert_ascii_to_str as tostr
from PIL import Image
import matplotlib.pyplot as plt

# return a loader of the dataset
lsp = dbc.load('leeds_sports_pose_extended')

# fetch data from the hdf5 metadata file (direct access)
img_fname = lsp.file['default/train/image_filenames'][0]  # image filename
filename = os.path.join(lsp.data_dir, tostr(img_fname))  # convert img_fname from ASCII encoding to string and craft the filename full path
img = Image.open(filename)  #load the image file
plt.imshow(img)  #plot the image
plt.show()

# display all keypoint names
print(tostr(lsp.file['default/train/keypoint_names'].value))
```


For now, fetching data is only done by these two methods. I had to do this to check compatibilities with python, lua and matlab APIs. Adding attributes for each field to the loader class will be the next thing to do for easier data fetching/slicing (haven't had the time until now to do it).

**Comment by tawnkramer** [comment]
Very nice examples and explanations, thank you. And thanks for making and
publishing this project!
